---
# - hosts: aws-sandbox
- hosts: "{{ host_name }}"
  vars:
      user_name: "{{user_name}}"
      host_name: "{{host_name}}"
      nodejs_version: "12.x"
      nodejs_install_npm_user: "{{ user_name }}"
      docker_install_compose: true
      docker_package_state: present
      docker_edition: 'ce'
      docker_users:
        - "{{user_name}}"
  roles:
    - { role: nover.ohmyzsh, ohmyzsh_theme: 'robbyrussell', become: true, ignore_errors: yes }
    - { role: geerlingguy.nodejs, become: yes, ignore_errors: yes } # optional
    - { role: andrewrothstein.yarn, become: yes, ignore_errors: yes }
    - { role: geerlingguy.docker, become: yes, ignore_errors: yes }
    - { role: andrewrothstein.kind, become: yes, ignore_errors: yes }
  tasks:
      - name: config fedora base vm
        include_role:
            name: config-vm
        vars:
            - host_name: "{{ host_name }}"
        when: fedora is defined
      - name: config debian based vm
        include_role:
            name: config-vm-apt
        vars:
            - host_name: "{{ host_name }}"
        when: fedora is not defined
      - name: install docker on fedora
        include_role:
            name: install-docker
        vars:
            - host_name: "{{ host_name }}"
        when: docker is defined
