---

- name: Check if Homebrew is already installed
  stat:
    path: /usr/local/bin/brew
  register: brew_installed

- name: install brew
  shell: yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew_installed.stat.exists

- name: Use ignore-pinned option while upgrading all
  community.general.homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin"
    upgrade_all: yes
    upgrade_options: ignore-pinned

- community.general.homebrew:
    name: ["htop", "fzf", "pyenv", "fpp", "stern", "kubectl", "nvm", "yarn", "kubectx", "kube-ps1"]
    state: present
    path: "/home/linuxbrew/.linuxbrew/bin"
