---
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  become: true

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https' ]
  become: true

- name: install packages
  ansible.builtin.package:
    name:
      - software-properties-common
      - build-essential
      - libssl-dev
      - libffi-dev
      - zlib1g-dev
      - libreadline-dev
      - libbz2-dev
      - libsqlite3-dev
      - llvm
      - libncurses5-dev 
      - ca-certificates
      - python3-dev
      - python3-venv
      - openjdk-11-jdk
      - gradle
  become: true

