---
- name: create .local/bin directory
  file:
    path: ~/.local/bin
    state: directory

- name: create misc directories
  file:
    state: directory
    path: "~/{{ item }}"
    mode: 0700
  loop:
    - .ansible/tmp
    - gitRepo
    - work

- name: download /etc/hosts file from someonewhocares.org
  get_url:
    url: https://someonewhocares.org/hosts/zero/hosts
    dest: /etc/hosts
    force: yes
    mode: 0644
  become: true

- include_tasks: "{{ ansible_os_family }}.yml"

- name: install packages
  ansible.builtin.package:
    name:
      - vim
      - unzip
      - wget
      - curl
      - byobu
      - bash-completion
      - jq
      - git
      - ripgrep
      - bzip2
      - ruby
      - virtualenv
      - python3-pip
      - python3-setuptools
      - python-is-python3
      - awscli
      - make
      - maven
      - neovim
    state: present
  become: true
