---
# - hosts: aws-sandbox
- hosts: "{{ host_name }}"
  vars:
      user_name: "{{user_name}}"
      host_name: "{{host_name}}"
      nodejs_version: "12.x"
      nodejs_install_npm_user: "{{ user_name }}"
      docker_install_compose: true
      docker_package_state: present
      docker_edition: 'ce'
      docker_users:
        - "{{user_name}}"
  roles:
    - ssh
    - base
    - homebrew
    - { role: nover.ohmyzsh, ohmyzsh_theme: 'robbyrussell', become: true, ignore_errors: yes }
    - { role: geerlingguy.nodejs, become: yes, ignore_errors: yes } # optional
    - { role: geerlingguy.docker, become: yes, ignore_errors: yes }
    - { role: andrewrothstein.kind, become: yes, ignore_errors: yes }
    - dotfiles
